#--------[ LORENS OSMAN ]--------#

#--------[ theLine_2LINE ]
# use ubuntuMono Nerd Font Mono 9
format = """
${custom.user}\
[   ](fg:#4b494f underline )\
${custom.host}\
[   ](fg:#4b494f underline )\
${custom.dir}\
$fill\
${custom.git}\
[   ](fg:#4b494f underline )\
$line_break\
$username\
[   ](fg:#4b494f underline )\
$hostname\
[   ](fg:#4b494f underline )\
${custom.directory}\
$fill\
$git_branch\
[   ](fg:#4b494f underline )\
$line_break\
$character
"""


#--------[CUSTOM COMMANDS]--------#

[custom.directory]
description = "Replace the default directory command"
command = """echo "${PWD/$HOME/~}" """
style = "fg:#33dd2d underline"
format = "[󰉋 $output]($style)"
when = "true"

[custom.dir]
description = "Dashes of directory "
command = """printf '%*s' "$(echo $(( $(pwd | sed "s|$HOME|~|" | wc -c) + 1 )))" '' | tr ' ' '_'"""
style = "fg:#33dd2d underline"
format = "[$output]($style)"
when = "true"


[custom.git]
description = "Replace the branch name with dashes"
command = "git rev-parse --abbrev-ref HEAD 2>/dev/null | wc -m | tr -d '\\n' | xargs -I {} seq -s '_' {} | tr -d '[:digit:]'| awk '{print $0 \"___\"}'"
when = "git rev-parse --abbrev-ref HEAD 2>/dev/null"
shell = ["bash", "--noprofile", "--norc"]
style = "fg:#e5e513 underline"
format = "[$output]($style)"

[custom.user]
description = "Dashes of username"
command = """printf '%*s' "$(echo $(echo $USER | tr -d '\n' | wc -c))" '' | tr ' ' '_' """
style = "#313fed  underline"
format = "[$output]($style)"
when = "true"

[custom.host]
description = "Dashes of hostname"
command = 'printf "%*s" "$(echo $(echo $HOST | tr -d "\n" | wc -c))" "" | tr " " "_" '
style = "red underline"
format = "[$output]($style)"
when = "true"

#--------[COMMANDS]

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname]( red underline)'
trim_at = '.companyname.com'
disabled = false

[username]
style_user = '#313fed underline'
style_root = 'black'
format = '[$user]($style)'
disabled = false
show_always = true

[fill]
symbol="⸏"
style = "fg:#4b494f underline"

[line_break]
disabled = false

[character]
success_symbol ='[](bold green)'
error_symbol ='[✖ ](bold red)'

#--------[GIT COMMANDS]

[git_branch]
symbol = "  "
style = "fg:#e5e513  underline"
format = "[$symbol$branch(:$remote_branch)]($style)"

