#--------[ LORENS OSMAN ]--------#


#--------[ starship:theLine:chain ]

format = """
$username\
[━━━](fg:#4b494f)\
$hostname\
[━━━](fg:#4b494f )\
${custom.directory}\
[━━━](fg:#4b494f)\
$fill\
$git_branch\
$line_break\
$character
"""


#--------[CUSTOM COMMANDS]

[custom.directory]
description = "Replace the default directory command"
command = """echo "${PWD/$HOME/~}" """
style = "white bold bg:#498547"
format = "[ 󰉋 $output ]($style)"
when = "true"


#--------[COMMANDS]

[username]
style_user = 'white bold bg:#474a85'
style_root = 'black'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname]( white bold bg:#854747 )'
trim_at = '.companyname.com'
disabled = false


[fill]
symbol="━"
style = "fg:#4b494f   "

[line_break]
disabled = false

[character]
success_symbol ='[━━](bold fg:#474a85)'
error_symbol ='[✖ ](bold red)'

#--------[GIT COMMANDS]

[git_branch]
symbol = "  "
style = "white bold bg:#857847 "
format = "[$symbol$branch(:$remote_branch) ]($style)"

