format = """
[  〢](fg:#3a86ff bg:#282c34 )\
${custom.home}\
${custom.folder}\
$directory\
$git_branch\
[ → ](fg:green  )\

"""
[directory]
style = "fg:#e3e5e5 bg:#dd4814"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "~/"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[custom.home]
when = "test $HOME = $PWD"
format = "[ 󰟒  ]( fg:red bg:#242424)"
[custom.folder]
when = "test $HOME != $PWD"
format = "[ 󰉋  ]( fg:#dd4814 bg:#242424)"




